// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7gQPin4cv8f8rahTBLuPV9YE9qLM44Ik',
    appId: '1:915522367090:web:c232f8d5dd4ee9fad01ceb',
    messagingSenderId: '915522367090',
    projectId: 'moora-project-80bcf',
    authDomain: 'moora-project-80bcf.firebaseapp.com',
    storageBucket: 'moora-project-80bcf.firebasestorage.app',
    measurementId: 'G-GBCVVJ00KG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJPHwdb2omwmuDTYT53Q8H9mv0Kkm6NYk',
    appId: '1:915522367090:android:cdd6dc3868cfe14fd01ceb',
    messagingSenderId: '915522367090',
    projectId: 'moora-project-80bcf',
    storageBucket: 'moora-project-80bcf.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7gQPin4cv8f8rahTBLuPV9YE9qLM44Ik',
    appId: '1:915522367090:web:82c451d906401952d01ceb',
    messagingSenderId: '915522367090',
    projectId: 'moora-project-80bcf',
    authDomain: 'moora-project-80bcf.firebaseapp.com',
    storageBucket: 'moora-project-80bcf.firebasestorage.app',
    measurementId: 'G-1P5LH2FV8G',
  );
}
